version: '3.8'

services:
  vod-catalog:
    build: .
    container_name: vod-catalog
    ports:
      - "5000:5000"
    environment:
      XTREAM_HOST: "http://XXXXX.XX"
      XTREAM_PORT: "8080"
      XTREAM_USERNAME: "XXXXXX"
      XTREAM_PASSWORD: "PASSWORD"
      DOWNLOAD_PATH_MOVIES: "/downloads/Filmy"
      DOWNLOAD_PATH_SERIES: "/downloads/Seriale"
      RETRY_COUNT: "3"
    volumes:
      - Chemin des téléchargements